Repository 2024-Winter-Bootcamp-team-K/AILIBI-Frontend, pull requests merged in 2025-01, with the labels that each got.

#8 feat: cicd, Docker 연동
  .github/workflows/ci.yml
  Dockerfile
  docker-compose.yml
  yarn.lock
Labels: ✨Feat

#10 fix: cicd, docker 연동 해제
  .github/workflows/ci.yml
  Dockerfile
  docker-compose.yml
  package.json
  yarn.lock
Labels: ❤️‍🔥BugFix

#12 design: 범인 지목 페이지 퍼블리싱
  package-lock.json
  package.json
  postcss.config.cjs
  public/fonts/BinggraeII-Bold.otf
  public/fonts/BinggraeII-Bold.woff
  public/images/ChoosePage.png
  public/images/FailPage.png
  src/App.tsx
  src/index.css
  src/pages/ChoosePage.tsx
  tailwind.config.js
  yarn.lock
Labels: 🎨Design

#16 design: 포기하기 페이지 퍼블리싱
  package-lock.json
  package.json
  public/images/GiveUpPage.png
  public/images/GiveUpPage2.png
  public/images/Suspect1.png
  public/images/WANTED.png
  public/images/WantedSuspect.png
  src/App.tsx
  src/pages/ChoosePage.tsx
  src/pages/FailPage.tsx
  src/pages/GiveUpPage.tsx
  tailwind.config.js
  yarn.lock
Labels: 🎨Design

#18 design: 성공 페이지 퍼블리싱
  public/images/SuccessPage.png
  public/images/SuccessPage2.png
  src/App.tsx
  src/pages/FailPage.tsx
  src/pages/SuccessPage.tsx
Labels: 🎨Design

#21 design: 엔딩 크레딧 퍼블리싱
  public/images/EndingPage.png
  src/App.tsx
  src/components/EndingPage.css
  src/pages/ChoosePage.tsx
  src/pages/EndingPage.tsx
  src/pages/SuccessPage.tsx
Labels: 🎨Design

#23 design: 시나리오 로딩 페이지 퍼블리싱
  public/fonts/intelone-mono-font-family-regular.ttf
  public/sounds/typing.mp3
  src/App.tsx
  src/index.css
  src/pages/InitChatPage.tsx
  src/pages/LoadingScenarioPage.tsx
  tailwind.config.js
Labels: 🎨Design

#28 design: 나는 바보다
  src/components/CardBack.css
  src/components/CenteredImage.css
  src/components/LoginBox.css
  src/components/SignupBox.css
  src/components/StartPage.css
  src/components/ZoomBackground.css
  src/pages/CardBack.tsx
  src/pages/CenteredImage.tsx
  src/pages/LoginBox.tsx
  src/pages/SignupBox.tsx
  src/pages/StartPage.tsx
  src/pages/ZoomBackground.tsx
  yarn.lock
Labels: 🎨Design

#31 fix: 명남이 똥 치우기
  public/images/CuttingWallet.png
  public/images/IdCard.png
  public/images/InitPage.png
  public/images/InitPageText.png
  public/images/Logo.png
  public/images/profile.png
  public/images/wallet.png
  src/App.tsx
  src/components/CardBack.css
  src/components/CenteredImage.css
  src/components/LoginBox.css
  src/components/SignupBox.css
  src/components/StartPage.css
  src/components/ZoomBackground.css
  src/pages/CardBack.tsx
  src/pages/CenteredImage.tsx
  src/pages/LoginBox.tsx
  src/pages/SignupBox.tsx
  src/pages/StartPage.tsx
  src/pages/ZoomBackground.tsx
Labels: ❤️‍🔥BugFix

#32 design: 증거, 용의자 페이지 퍼블리싱
  public/images/Evidence1.png
  public/images/Evidence2.png
  public/images/Evidence_back.png
  public/images/Suspect_back.png
  public/images/WantedSuspect.png
  public/images/back.svg
  public/images/note.png
  src/App.tsx
  src/pages/EvidencePage.tsx
  src/pages/PlayPage.tsx
  src/pages/SuspectPage.tsx
Labels: 🎨Design

#34 chore:환경변수설정
  src/pages/StartPage.tsx
  tsconfig.app.json
Labels: ⚙️ Chore

#38 design: 시작, 로그인, 회원가입
  public/mp4/Shot.mp4
  public/sounds/door.mp3
  public/sounds/foot.mp3
  public/sounds/rain.mp3
  src/App.tsx
  src/components/CardBack.css
  src/components/LoginBox.css
  src/components/SignupBox.css
  src/components/VideoPage.css
  src/pages/CenteredImage.tsx
  src/pages/LoginBox.tsx
  src/pages/SignupBox.tsx
  src/pages/VideoPage.tsx
Labels: 🎨Design

#39 fix: 각 페이지 오류 수정
  public/sounds/Choose.mp3
  public/sounds/Fail.mp3
  public/sounds/Stamp.mp3
  src/components/EndingPage.css
  src/components/SignupBox.css
  src/components/StartPage.css
  src/components/ZoomBackground.css
  src/pages/ChoosePage.tsx
  src/pages/EndingPage.tsx
  src/pages/FailPage.tsx
  src/pages/GiveUpPage.tsx
  src/pages/LoadingScenarioPage.tsx
  src/pages/SignupBox.tsx
  src/pages/SuccessPage.tsx
  src/pages/SuspectPage.tsx
  tsconfig.json
Labels: ❤️‍🔥BugFix

#41 Design/#35 용의자 심문 페이지
  public/images/ChatPage_back.png
  public/images/Mic.svg
  public/images/Paper.png
  src/App.tsx
  src/pages/ChattingPage.tsx
  src/pages/SuspectPage.tsx
Labels: 🎨Design

#43 chore:로그인 시작 페이지 합치기
  src/App.tsx
  src/components/CardBack.css
  src/components/CenteredImage.css
  src/components/LogInPage.css
  src/components/LoginBox.css
  src/components/StartPage.css
  src/components/VideoPage.css
  src/components/ZoomBackground.css
  src/pages/CardBack.tsx
  src/pages/CenteredImage.tsx
  src/pages/LogInPage.tsx
  src/pages/LoginBox.tsx
  src/pages/StartPage.tsx
  src/pages/ZoomBackground.tsx
Labels: ⚙️ Chore

#47 design:미완성
  public/images/CheckEv.png
  public/images/Icon.png
  public/images/Note2.png
  public/images/PlayHistory.png
  public/images/Success.png
  public/images/background.jpg
  public/images/paper2.png
  public/sounds/book.mp3
  public/sounds/fear.wav
  public/sounds/pencil.mp3
  src/App.tsx
  src/pages/HistoryPage.tsx
  src/pages/MainPage.tsx
  src/pages/MakeScenarioPage.tsx
  src/pages/NextPage.tsx
  src/pages/NextPage2.tsx
  src/pages/NotePage.tsx
Labels: 🎨Design

#49 design: 로그인 디테일 개선
  public/sounds/gun.mp3
  public/sounds/startbgm.mp3
  src/components/LogInPage.css
  src/components/SignupBox.css
  src/pages/LogInPage.tsx
Labels: 🎨Design

#51 design: 페이지 전환 및 분리
  src/App.tsx
  src/components/SignupBox.css
  src/pages/LoginBox.tsx
  src/pages/SignupBox.tsx
  src/pages/VideoPage.tsx
Labels: 🎨Design

#55 design: 엔딩 페이지 디테일 수정
  src/components/EndingPage.css
  src/pages/EndingPage.tsx
Labels: 🎨Design

#57 design:수정
  src/pages/HistoryPage.tsx
  src/pages/MainPage.tsx
  src/pages/MakeScenarioPage.tsx
  src/pages/NextPage.tsx
  src/pages/NextPage2.tsx
Labels: 🎨Design

#60 design: 추리 노트 디자인
  package-lock.json
  package.json
  src/App.tsx
  src/pages/NotePage.tsx
  yarn.lock
Labels: 🎨Design

#62 design: 메인 페이지 디자인 디테일 및 반응형 디자인, BGM 추가
  public/images/background2.jpg
  public/sounds/Choose7.mp3
  public/sounds/mainbgm.mp3
  src/App.tsx
  src/pages/LoadingScenarioPage.tsx
  src/pages/MainAudioContext.tsx
  src/pages/MainPage.tsx
Labels: 🎨Design

#65 히스토리 디자인 디테일 수정 및 정적
  package.json
  src/pages/HistoryPage.tsx
  src/pages/NextPage.tsx
  src/pages/NextPage2.tsx
  yarn.lock
Labels: 🎨Design

#67 design: 결과 페이지 UI 및 지갑 이미지 수정
  public/images/CuttingWallet(2).png
  public/images/CuttingWallet.png
  public/images/Newspaper.png
  public/images/realpaper.png
  public/images/wallet(2).png
  public/images/wallet.png
  src/pages/LogInPage.tsx
  src/pages/ResultPage.tsx
Labels: 🎨Design

#69 design: 용의자 페이지 버튼 수정
  src/pages/SuspectPage.tsx
Labels: 🎨Design

#71 Design/#53 로그인, 회원가입. 초기진술, 시나리오 생성 페이지 디자인 개선
  src/components/LogInPage.css
  src/components/SignupBox.css
  src/pages/HistoryPage.tsx
  src/pages/InitChatPage.tsx
  src/pages/LogInPage.tsx
  src/pages/MakeScenarioPage.tsx
  src/pages/NextPage.tsx
  src/pages/SignupBox.tsx
Labels: 🎨Design

#74 노트 디자인 수정 및 다른 페이지와의 연동 완료
  public/images/hand.jpg
  public/sounds/Styping.mp3
  public/sounds/note.wav
  src/pages/EvidencePage.tsx
  src/pages/HistoryPage.tsx
  src/pages/NextPage.tsx
  src/pages/NextPage2.tsx
  src/pages/NotePage.tsx
  src/pages/PlayPage.tsx
  src/pages/SuspectPage.tsx
Labels: 🎨Design

#76 아이콘 눌렀을시에 노트 체이지로 가는 부분 수정
  src/pages/EvidencePage.tsx
  src/pages/HistoryPage.tsx
  src/pages/NextPage.tsx
  src/pages/NextPage2.tsx
  src/pages/PlayPage.tsx
  src/pages/SuspectPage.tsx
Labels: 🎨Design

#78 design: 심문페이지 디테일 수정
  package-lock.json
  package.json
  src/pages/ChattingPage.tsx
  yarn.lock
Labels: 🎨Design

#80 Design/#77 로그인 페이지 디자인을 로그인 박스에 적용
  src/pages/LoginBox.tsx
Labels: 🎨Design

#82 design: 로딩 페이지 수정
  src/pages/EvidencePage.tsx
  src/pages/LoadingScenarioPage.tsx
Labels: 🎨Design

#87 design: 플레이 기록 리스트 드롭다운 UI
  src/pages/LeftPage.tsx
  src/pages/MainPage.tsx
  src/pages/PlayHistoryPage.tsx
  src/pages/RightPage.tsx
Labels: 🎨Design

#89 design: 시작 페이지 디테일 수정
  public/images/InitPageText.png
  public/images/click.png
  src/components/LogInPage.css
  src/pages/LogInPage.tsx
Labels: 🎨Design

#90 design: 결과 페이지 디자인 개선
  src/pages/ResultPage.tsx
  src/pages/RightPage.tsx
Labels: 🎨Design

#98 Feat/#95 회원가입 로그인 api 연동
  package-lock.json
  package.json
  src/pages/LogInPage.tsx
  src/pages/LoginBox.tsx
  src/pages/SignupBox.tsx
  yarn.lock
Labels: ✨Feat

#96 feat:api연동-시나리오생성,노트,챗,로딩
  package-lock.json
  package.json
  src/App.tsx
  src/pages/ChattingPage.tsx
  src/pages/LoadingScenarioPage.tsx
  src/pages/MakeScenarioPage.tsx
  src/pages/NotePage.tsx
  src/services/apiService.ts
  vite.config.ts
Labels: ✨Feat

#103 feat: 초기진술페이지 api 연동
  src/App.tsx
  src/pages/InitChatPage.tsx
  src/pages/LogInPage.tsx
  src/pages/LoginBox.tsx
  src/pages/SignupBox.tsx
Labels: ✨Feat

#97 feat: 용의자, 증거 목록, 범인 찾기 API 연동
  src/App.tsx
  src/hooks/axiosInstance.ts
  src/pages/ChoosePage.tsx
  src/pages/EvidencePage.tsx
  src/pages/HistoryNote.tsx
  src/pages/HistoryPopUp.tsx
  src/pages/LeftPage.tsx
  src/pages/MainPage.tsx
  src/pages/NotePage.tsx
  src/pages/PlayHistoryPage.tsx
  src/pages/ResultLoadingPage.tsx
  src/pages/RightPage.tsx
  src/pages/SuspectPage.tsx
  yarn.lock
Labels: ✨Feat

#109 feat: UserId 저장 기능 구현
  src/App.tsx
  src/hooks/UserContext.tsx
  src/pages/LogInPage.tsx
  src/pages/MainPage.tsx
  src/pages/PlayHistoryPage.tsx
  src/pages/SignupBox.tsx
  src/pages/VideoPage.tsx
Labels: ✨Feat

#101 시나리오생성 기능 구현 완
  src/pages/LoadingScenarioPage.tsx
  src/pages/MakeScenarioPage.tsx
Labels: ✨Feat

#112 feat: 플레이 페이지 api 연동 및 기능구현
  src/App.tsx
  src/pages/PlayPage.tsx
Labels: ✨Feat

#113 feat: 결과 페이지 API 연동
  src/App.tsx
  src/pages/ResultPage.tsx
Labels: ✨Feat

#115 feat: 플레이 페이지 기능구현 수정
  src/pages/PlayPage.tsx
Labels: ✨Feat

#117 Feat/#110 기능 구현
  src/App.tsx
  src/pages/ChoosePage.tsx
  src/pages/EndingPage.tsx
  src/pages/ResultLoadingPage.tsx
  src/pages/SuspectPage.tsx
Labels: ✨Feat

#123 feat: 심문 페이지에서 용의자 페이지로 돌아가기
  src/pages/ChattingPage.tsx
Labels: ✨Feat

#126 feat: 초기진술 페이지 기능구현 추가
  src/pages/InitChatPage.tsx
Labels: ✨Feat

#128 Feat/#121 로딩 메세지 제거, 시나리오 생성 페이지 연결
  src/pages/EvidencePage.tsx
  src/pages/HistoryPopUp.tsx
  src/pages/MainPage.tsx
  src/pages/MakeScenarioPage.tsx
  src/pages/NotePage.tsx
  src/pages/PlayHistoryPage.tsx
  src/pages/PlayPage.tsx
  src/pages/ResultPage.tsx
  src/pages/SuspectPage.tsx
Labels: ✨Feat

#131 design: 초기진술 디자인 수정
  src/pages/InitChatPage.tsx
Labels: 🎨Design

#132 Feat/#127 탐정 노트 개선
  src/App.tsx
  src/pages/NotePage.tsx
  src/pages/PlayPage.tsx
  src/services/apiService.ts
Labels: ✨Feat

#136 feat: 채팅 페이지 tts 연동
  src/pages/ChattingPage.tsx
  src/pages/TTSService.tsx
Labels: ✨Feat

#138 Feat/#134 로딩, 초기진술, 노트, 증거 페이지 기능 구현
  src/pages/EvidencePage.tsx
  src/pages/InitChatPage.tsx
  src/pages/LoadingScenarioPage.tsx
  src/pages/NotePage.tsx
  src/pages/SuspectPage.tsx
Labels: ✨Feat

#141 feat: 시나리오 생성 날짜, 시간 제한 기능 구현
  src/pages/MakeScenarioPage.tsx
Labels: ✨Feat

#143 증거 페이지 디테일에서 글씨 넘어가는거 줄바꿈
  index.html
  public/logo.png
  src/pages/EvidencePage.tsx
  src/services/apiService.ts
Labels: 🎨Design

#146 refactor: 시나리오 생성 로직 수정
  src/services/apiService.ts
Labels: ✨Feat

#148 feat: 채팅 페이지 기능구현
  src/pages/ChattingPage.tsx
Labels: ✨Feat

#149 Feat/#144 히스토리 페이지 채팅 Q, A, Q, A 로 나오게 하기, 시나리오 생성 날짜 placeholder 추가
  src/pages/HistoryPopUp.tsx
  src/pages/MakeScenarioPage.tsx
  src/pages/RightPage.tsx
Labels: ✨Feat

#151 메인페이지 카드 이팩트 추가
  src/pages/MainPage.tsx
Labels: 🎨Design

#155 메인페이지 볼륨기능 추가
  src/App.tsx
  src/pages/MainAudioContext.tsx
  src/pages/MainPage.tsx
Labels: ✨Feat

#158 feat: 히스토리 페이지 깨진 UI 수정
  package-lock.json
  package.json
  public/images/CheckEv.png
  src/pages/HistoryPopUp.tsx
  src/pages/LeftPage.tsx
  src/pages/PlayHistoryPage.tsx
  src/pages/RightPage.tsx
  tailwind.config.js
  yarn.lock
Labels: ✨Feat

#160 feat:볼륨기능 우선 보류
  src/App.tsx
  src/pages/MainAudioContext.tsx
  src/pages/MainPage.tsx
  src/pages/MakeScenarioPage.tsx
Labels: ✨Feat

#165 fix: 오타 수정
  src/pages/EndingPage.tsx
Labels: ❤️‍🔥BugFix

#166 Feat/#161 히스토리 페이지 반응형으로
  src/pages/HistoryPopUp.tsx
Labels: ✨Feat

#168 fix: 로그인 박스 수정
  src/pages/LoginBox.tsx
Labels: ❤️‍🔥BugFix

#170 refactor: 필요 없는 페이지 및 이미지 삭제
  public/images/FailPage.png
  public/images/Newspaper.png
  public/images/hand.jpg
  src/pages/HistoryPage.tsx
  src/pages/NextPage.tsx
  src/pages/NextPage2.tsx
Labels: 🔨Refactor

#175 design: 결과 페이지 디자인 개선
  src/pages/ResultPage.tsx
Labels: 🎨Design

#177 fix: 메인 페이지 userID 하드코딩 픽스
  src/hooks/UserContext.tsx
  src/pages/MainPage.tsx
Labels: ❤️‍🔥BugFix

#178 design: 추리노트 수정
  src/pages/NotePage.tsx
Labels: 🎨Design

#180 fix: 메인 페이지 머지 오류 해결
  src/pages/MainPage.tsx
Labels: ❤️‍🔥BugFix

#192 feat: 엔딩페이지 플레이 시간 및 진행한 심문 횟수 수정
  src/pages/ChattingPage.tsx
  src/pages/EndingPage.tsx
Labels: ✨Feat

#188 design: 증거 페이지 조사하기 클릭 시 하단 문구 잘리는 디자인 수정
  src/pages/ChattingPage.tsx
  src/pages/EvidencePage.tsx
Labels: 🎨Design

#186 design: 심문 페이지 초기 진술 짤리는 디자인 수정
  src/pages/ChattingPage.tsx
Labels: 🎨Design

#193 Design/#181 메인페이지 디자인 수정
  public/images/papyrus.png
  src/pages/LoadingScenarioPage.tsx
  src/pages/MainPage.tsx
Labels: 🎨Design

#195 refactor: 엔딩 페이지 미사용 상태 변수 처리
  src/pages/EndingPage.tsx
Labels: 🔨Refactor

#197 feat: 범인 지목 팝업
  src/pages/SuspectPage.tsx
Labels: ✨Feat

#202 Feat/#201 미니게임 효과음 추가
  package-lock.json
  package.json
  public/images/gameIcon.png
  public/images/minigame1.png
  public/images/minigame2.png
  public/images/minigame3.png
  public/images/minigame3A.png
  public/sounds/bomb.mp3
  public/sounds/correct.mp3
  public/sounds/laser.mp3
  public/sounds/poka.mp3
  src/App.tsx
  src/index.css
  src/pages/GamePage1.tsx
  src/pages/GamePage2.tsx
  src/pages/GamePage3.tsx
  src/pages/LoadingScenarioPage.tsx
  yarn.lock
Labels: ✨Feat

#184 feat:미니게임 틀린그림 찾기
  package-lock.json
  package.json
  public/images/gameIcon.png
  public/images/minigame1.png
  public/images/minigame2.png
  public/images/minigame3.jpg
  src/App.tsx
  src/index.css
  src/pages/GamePage1.tsx
  src/pages/GamePage2.tsx
  src/pages/GamePage3.tsx
  src/pages/LoadingScenarioPage.tsx
  yarn.lock
Labels: ✨Feat

#203 Design/#198 용의자, 증거 페이지 디자인 개선
  src/pages/EvidencePage.tsx
  src/pages/SuspectPage.tsx
Labels: 🎨Design

#205 design: 엔딩페이지
  src/pages/EndingPage.tsx
Labels: 🎨Design

#208 fix: 미니게임 수정
  public/images/gameIcon.png
  src/pages/GamePage1.tsx
  src/pages/GamePage2.tsx
  src/pages/GamePage3.tsx
  src/pages/LoadingScenarioPage.tsx
Labels: ❤️‍🔥BugFix

#211 design: 범인 지목 팝업 디자인
  src/pages/SuspectPage.tsx
Labels: 🎨Design

#209 design: 메인페이지 버튼 롤백
  src/pages/MainPage.tsx
Labels: 🎨Design

#213 feat: 스토쿠 게임 추가
  src/pages/GamePage2.tsx
  src/pages/LoadingScenarioPage.tsx
  src/pages/SudokuGame.tsx
Labels: ✨Feat

#215 fix: build 오류 및 BGM 중복 수정 / feat: 엔터 키 진입 및 로딩 바 개선
  src/App.tsx
  src/components/LogInPage.css
  src/components/SignupBox.css
  src/pages/LoadingScenarioPage.tsx
  src/pages/LogInPage.tsx
  src/pages/LoginBox.tsx
  src/pages/SignupBox.tsx
Labels: ❤️‍🔥BugFix, ✨Feat

#218 fix: 시나리오 생성 userID 하드 코딩 수정
  src/pages/MakeScenarioPage.tsx
Labels: ❤️‍🔥BugFix

#222 fix: yarn, npm 충돌 오류
  package-lock.json
  yarn.lock
Labels: ❤️‍🔥BugFix

#220 fix: 초기진술 페이지 이미지 내려가지 않도록 수정
  src/pages/InitChatPage.tsx
Labels: ❤️‍🔥BugFix

#223 design: 스토쿠 게임 디자인 개선, 게임 선택 창 개선
  src/pages/LoadingScenarioPage.tsx
  src/pages/SudokuGame.tsx
Labels: 🎨Design

#226 feat:슈팅게임 오류수정 및 반응형
  src/pages/GamePage1.tsx
  src/pages/LoadingScenarioPage.tsx
Labels: ✨Feat

#227 feat: 결과 페이지 도장 애니메이션 추가
  src/pages/ResultPage.tsx
Labels: ✨Feat

#237 fix:로그인 엔드포인트 수정
  src/App.tsx
  src/pages/MainPage.tsx
  src/pages/SignupBox.tsx
Labels: ❤️‍🔥BugFix

#235 design: 시나리오 페이지 , 추리 노트 디자인 개선
  public/images/minigame1.png
  public/images/minigame3A.png
  public/images/note.png
  src/pages/MakeScenarioPage.tsx
  src/pages/NotePage.tsx
Labels: 🎨Design

#240 fix: 오디오 중복 재생 오류
  src/pages/MainAudioContext.tsx
Labels: ❤️‍🔥BugFix

#242 fix: 타이핑 오류 및 오디오 토글 오류
  src/pages/LoadingScenarioPage.tsx
  src/pages/MainAudioContext.tsx
Labels: ❤️‍🔥BugFix

#245 design: 21: 9 반응형 추가, 용의자, 엔딩 크래딧 개선
  src/components/LogInPage.css
  src/pages/ChattingPage.tsx
  src/pages/EndingPage.tsx
  src/pages/MainPage.tsx
  src/pages/MakeScenarioPage.tsx
Labels: 🎨Design

#247 design: 증거, 용의자 페이지 반응형
  src/pages/EvidencePage.tsx
  src/pages/SuspectPage.tsx
Labels: 🎨Design

#249 design: 용의자 페이지 버튼 글자 크기
  src/pages/SuspectPage.tsx
Labels: 🎨Design

#244 fix: 타이핑 오류 수정 v2
  src/pages/LoadingScenarioPage.tsx
Labels: ❤️‍🔥BugFix

#251 fix: tts 하드코딩 수정
  src/pages/ChattingPage.tsx
  src/pages/LoadingScenarioPage.tsx
  src/pages/TTSService.tsx
Labels: ❤️‍🔥BugFix

#255 design: 증거 페이지 증거 크기 정상화
  src/pages/EvidencePage.tsx
Labels: 🎨Design

#256 fix: 레나 멘토님 이름 오타 수정
  src/pages/EndingPage.tsx
Labels: ❤️‍🔥BugFix

#258 fix: 다른 난이도 선택되는 오류 수정
  src/pages/MakeScenarioPage.tsx
Labels: ❤️‍🔥BugFix
